# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: ibm
name: csm
version: 0.0.1
readme: README.md
authors:
  - blearandy (github.com/blearandy)
description: Ansible Collection for IBM Copy Services Manager
license_file: LICENSE
tags:
  - ibm
  - ds8000
  - flashsystem
  - storage
  - spectrum_virtualize
repository: https://github.com/ansible-collections/ibm.csm
documentation: https://github.com/ansible-collection/ibm.csm
homepage: https://github.com/ansible-collections/ibm.csm
issues: https://github.com/ansible-collections/ibm.csm/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections_distributing.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
